import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';
import { Amplify } from 'aws-amplify';
import amplifyconfig from './amplifyconfiguration.json';

// Configure Amplify once at startup using the auto-generated config
// (generated by `amplify push` — do not edit manually)
Amplify.configure(amplifyconfig);

bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));
