import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';
import { Amplify } from 'aws-amplify';
import amplifyconfig from './amplifyconfiguration.json';

// Configure Amplify once using the file auto-generated by `amplify push`.
// Do not edit amplifyconfiguration.json manually.
Amplify.configure(amplifyconfig);

bootstrapApplication(AppComponent, appConfig)
  .catch(err => console.error(err));
